name: easy_care
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.11.5


dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0

  cupertino_icons: ^1.0.8

  image_picker: ^1.1.2  # 사진 촬영 및 갤러리 선택
  google_mlkit_text_recognition: ^0.15.1 # OCR 글자 인식 (M1 대응 업데이트)
  kakao_flutter_sdk_user: ^1.9.5 # 카카오 로그인
  fl_chart: ^0.69.0 # 통계 그래프
  table_calendar: ^3.1.2 # 달력 기능
  provider: ^6.1.2 # 데이터 상태 관리
  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0
  shared_preferences: ^2.5.5
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0
  excel: ^4.0.6
  path_provider: ^2.1.5
  share_plus: ^13.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  # .env 등록
  assets:
    - .env
